"""Generate ROADMAP.md from ranked tasks + opportunities."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path


def generate_roadmap(tasks: list[dict], opportunities: list[dict], project_root: Path) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    pending = [t for t in tasks if t.get("status") == "pending" and t.get("score", 0) > 0]
    pending.sort(key=lambda t: t.get("priority", 99))

    now_tasks  = [t for t in pending if t.get("score", 0) >= 70]
    next_tasks = [t for t in pending if 30 <= t.get("score", 0) < 70]
    later_tasks = [t for t in pending if t.get("score", 0) < 30]

    opp_now  = [o for o in opportunities if o.get("phase") == "now"]
    opp_next = [o for o in opportunities if o.get("phase") == "next"]
    opp_later = [o for o in opportunities if o.get("phase") == "later"]

    lines = [
        "# Flora — Roadmap",
        f"_Auto-generated by Self-Improvement Engine · {now}_",
        "",
        "---",
        "",
        "## Now — Fix First",
        "_High-impact issues that should be addressed immediately._",
        "",
    ]

    for t in now_tasks[:5]:
        lines.append(f"- [ ] **{t['title']}** _(score: {t.get('score', 0)}, effort: {t.get('effort', '?')})_")
    for o in opp_now[:3]:
        lines.append(f"- [ ] **{o['title']}** _(opportunity, impact: {o.get('impact', '?')})_")
    lines.append("")

    lines += ["## Next — This Month", "_Medium-priority improvements._", ""]
    for t in next_tasks[:6]:
        lines.append(f"- [ ] **{t['title']}**")
    for o in opp_next[:4]:
        lines.append(f"- [ ] **{o['title']}** _(opportunity)_")
    lines.append("")

    lines += ["## Later — Backlog", "_Lower-priority and visionary items._", ""]
    for t in later_tasks[:5]:
        lines.append(f"- [ ] {t['title']}")
    for o in opp_later[:3]:
        lines.append(f"- [ ] {o['title']} _(opportunity)_")
    lines.append("")

    doc = "\n".join(lines)
    (project_root / "ROADMAP.md").write_text(doc)
    return doc
