"""add_learning_jobs_table

Revision ID: 1d806e29bd96
Revises: f5e1c52b7fb4
Create Date: 2026-07-10 10:55:39.484103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d806e29bd96'
down_revision: Union[str, None] = 'f5e1c52b7fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_jobs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('documents_scanned', sa.Integer(), nullable=False),
    sa.Column('memories_created', sa.Integer(), nullable=False),
    sa.Column('kg_nodes_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_jobs_status'), 'learning_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_learning_jobs_workspace_id'), 'learning_jobs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_jobs_workspace_id'), table_name='learning_jobs')
    op.drop_index(op.f('ix_learning_jobs_status'), table_name='learning_jobs')
    op.drop_table('learning_jobs')
    # ### end Alembic commands ###
