"""add_stock_tables

Revision ID: f5e1c52b7fb4
Revises: aae1e08d158c
Create Date: 2026-07-10 10:51:38.797561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5e1c52b7fb4'
down_revision: Union[str, None] = 'aae1e08d158c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tickers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_date'), 'daily_reports', ['date'], unique=False)
    op.create_index(op.f('ix_daily_reports_status'), 'daily_reports', ['status'], unique=False)
    op.create_index(op.f('ix_daily_reports_workspace_id'), 'daily_reports', ['workspace_id'], unique=False)
    op.create_table('stock_analyses',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('key_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_analyses_analysis_type'), 'stock_analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_stock_analyses_date'), 'stock_analyses', ['date'], unique=False)
    op.create_index(op.f('ix_stock_analyses_ticker'), 'stock_analyses', ['ticker'], unique=False)
    op.create_index(op.f('ix_stock_analyses_workspace_id'), 'stock_analyses', ['workspace_id'], unique=False)
    op.create_table('stock_holdings',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_price_date', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_holdings_ticker'), 'stock_holdings', ['ticker'], unique=False)
    op.create_index(op.f('ix_stock_holdings_user_id'), 'stock_holdings', ['user_id'], unique=False)
    op.create_index(op.f('ix_stock_holdings_workspace_id'), 'stock_holdings', ['workspace_id'], unique=False)
    op.create_table('stock_watchlists',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_watchlists_user_id'), 'stock_watchlists', ['user_id'], unique=False)
    op.create_index(op.f('ix_stock_watchlists_workspace_id'), 'stock_watchlists', ['workspace_id'], unique=False)
    op.create_table('stock_watchlist_items',
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['stock_watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_watchlist_items_ticker'), 'stock_watchlist_items', ['ticker'], unique=False)
    op.create_index(op.f('ix_stock_watchlist_items_watchlist_id'), 'stock_watchlist_items', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_watchlist_items_watchlist_id'), table_name='stock_watchlist_items')
    op.drop_index(op.f('ix_stock_watchlist_items_ticker'), table_name='stock_watchlist_items')
    op.drop_table('stock_watchlist_items')
    op.drop_index(op.f('ix_stock_watchlists_workspace_id'), table_name='stock_watchlists')
    op.drop_index(op.f('ix_stock_watchlists_user_id'), table_name='stock_watchlists')
    op.drop_table('stock_watchlists')
    op.drop_index(op.f('ix_stock_holdings_workspace_id'), table_name='stock_holdings')
    op.drop_index(op.f('ix_stock_holdings_user_id'), table_name='stock_holdings')
    op.drop_index(op.f('ix_stock_holdings_ticker'), table_name='stock_holdings')
    op.drop_table('stock_holdings')
    op.drop_index(op.f('ix_stock_analyses_workspace_id'), table_name='stock_analyses')
    op.drop_index(op.f('ix_stock_analyses_ticker'), table_name='stock_analyses')
    op.drop_index(op.f('ix_stock_analyses_date'), table_name='stock_analyses')
    op.drop_index(op.f('ix_stock_analyses_analysis_type'), table_name='stock_analyses')
    op.drop_table('stock_analyses')
    op.drop_index(op.f('ix_daily_reports_workspace_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_status'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_date'), table_name='daily_reports')
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
