"""Auto-generate PROJECT_STATUS.md from scan results."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..models import Finding, Task

_SEV_PREFIX = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "⚪"}


class StatusReporter:
    def __init__(self, project_root: Path) -> None:
        self.output_path = project_root / "PROJECT_STATUS.md"

    def generate(
        self,
        findings: list[Finding],
        tasks: list[Task],
        atlas: dict[str, Any],
    ) -> str:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        metrics = atlas.get("current_metrics", {})
        history = atlas.get("metrics_history", [])
        scan_count = atlas.get("scan_count", 0)

        active = [f for f in findings]  # all findings passed in are from the current scan
        by_sev: dict[str, list[Finding]] = {}
        for f in active:
            by_sev.setdefault(f.severity, []).append(f)
        by_cat: dict[str, list[Finding]] = {}
        for f in active:
            by_cat.setdefault(f.category, []).append(f)

        lines: list[str] = [
            "# Flora — Project Status",
            f"_Auto-generated by Self-Improvement Engine · {now} · Scan #{scan_count}_",
            "",
            "---",
            "",
        ]

        # ── Overview metrics ─────────────────────────────────────────────────
        lines += [
            "## Overview",
            "",
            "| Metric | Value |",
            "|---|---|",
            f"| Files scanned | {metrics.get('files_scanned', '—')} |",
            f"| Python files | {metrics.get('python_files', '—')} |",
            f"| TypeScript files | {metrics.get('typescript_files', '—')} |",
            f"| Total lines | {metrics.get('total_lines', 0):,} |",
            f"| Active findings | {len(active)} |",
            f"| Critical | {len(by_sev.get('critical', []))} |",
            f"| High | {len(by_sev.get('high', []))} |",
            f"| Medium | {len(by_sev.get('medium', []))} |",
            f"| Low | {len(by_sev.get('low', []))} |",
            "",
        ]

        # Trend from history
        if len(history) >= 2:
            delta = history[-1].get("total_findings", 0) - history[-2].get("total_findings", 0)
            if delta < 0:
                lines.append(f"> **Trend:** ↓ {abs(delta)} findings resolved since last scan\n")
            elif delta > 0:
                lines.append(f"> **Trend:** ↑ {delta} new findings since last scan\n")
            else:
                lines.append("> **Trend:** → no change since last scan\n")
            lines.append("")

        # ── Critical + High findings ─────────────────────────────────────────
        urgent = by_sev.get("critical", []) + by_sev.get("high", [])
        if urgent:
            lines += ["## Critical & High Findings", ""]
            for f in urgent[:15]:
                pfx = _SEV_PREFIX.get(f.severity, "⚪")
                loc = f"`{f.file}:{f.line}`" if f.line else f"`{f.file}`"
                lines.append(f"- {pfx} **{f.severity.upper()}** {loc}  ")
                lines.append(f"  {f.message}")
                if f.detail:
                    lines.append(f"  > _{f.detail}_")
            lines.append("")

        # ── Priority task queue ───────────────────────────────────────────────
        pending = sorted(
            [t for t in tasks if t.status == "pending" and t.score > 0],
            key=lambda t: t.priority,
        )
        if pending:
            lines += [
                "## Priority Task Queue",
                "",
                "| # | Title | Category | Impact | Effort | Score |",
                "|---|---|---|---|---|---|",
            ]
            for t in pending[:15]:
                title = t.title[:55] + ("…" if len(t.title) > 55 else "")
                lines.append(
                    f"| {t.priority} | {title} | {t.category} | {t.impact} | {t.effort} | {t.score} |"
                )
            lines.append("")

        # ── Findings by category ─────────────────────────────────────────────
        if by_cat:
            lines += ["## Findings by Category", ""]
            for cat in sorted(by_cat, key=lambda c: -len(by_cat[c])):
                cat_list = by_cat[cat]
                label = cat.replace("_", " ").title()
                lines.append(f"### {label} ({len(cat_list)})")
                for f in cat_list[:5]:
                    loc = f":{f.line}" if f.line else ""
                    lines.append(f"- `{f.file}{loc}` — {f.message}")
                if len(cat_list) > 5:
                    lines.append(f"- _{len(cat_list) - 5} more…_")
                lines.append("")

        # ── Recommended next action ───────────────────────────────────────────
        if pending:
            top = pending[0]
            lines += [
                "---",
                "",
                "## Recommended Next Action",
                "",
                f"### {top.title}",
                "",
                top.description,
                "",
                "**Acceptance criteria:**",
            ]
            for c in top.acceptance_criteria:
                lines.append(f"- {c}")
            lines += [
                "",
                f"_Score: {top.score} · Impact: {top.impact} · Effort: {top.effort}_",
                "",
            ]

        # ── Architecture overview (stable section) ───────────────────────────
        lines += _architecture_section()

        doc = "\n".join(lines)
        self.output_path.write_text(doc)
        return doc


def _architecture_section() -> list[str]:
    return [
        "---",
        "",
        "## Existing Architecture",
        "",
        "```",
        "Flora/",
        "├── apps/",
        "│   ├── api/     FastAPI + Celery + pgvector (Python 3.12)",
        "│   └── web/     Next.js 15 App Router (TypeScript)",
        "└── packages/",
        "    ├── types/   Shared TypeScript interfaces",
        "    ├── ui/      shadcn/ui component library",
        "    └── config/  Shared eslint / tsconfig / tailwind",
        "```",
        "",
        "**Data flow:** Source upload → Celery ingest → Voyage AI embed → pgvector  ",
        "**Search:** pgvector cosine + tsvector BM25 → RRF fusion → top 8 chunks  ",
        "**Chat:** RAG context assembly → OpenAI/Anthropic SSE stream → persist message  ",
        "",
    ]
